# Created by Nelson Durrant, Feb 2025
pvt_to_nsf: # converts ublox PosVelTime to NavSatFix we can use in the navsat_transform_node
  ros__parameters:
    # IMPORTANT! The covariance defines how closely our EFK output follows the GPS data
    # Since we have reliable RTK GPS data, we may want to trust it more than the GPS reports
    # Thus we can use a tuning factor to adjust the covariance (smaller means more trust)
    gps_covariance_factor: 0.01

imu_filter_madgwick: # combines IMU and magnetometer data from the ZED
  ros__parameters:
    use_mag: True
    use_magnetic_field_msg: True
    world_frame: 'enu' # to match robot_localization
    publish_tf: False
    publish_debug_topics: False

ekf_filter_node_odom:
# This publishes the odom->base_link transform
# The position calculated here needs to be continuous, but not necessarily incredibly accurate
# https://robotics.stackexchange.com/questions/109942/odometry-with-robot-localization-using-gps-and-imu-not-encoders
  ros__parameters:
    frequency: 15.0 # The Jetson struggles to run faster than this
    two_d_mode: true # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link # base_footprint is used in Gazebo
    world_frame: odom

    # https://docs.nav2.org/tutorials/docs/integrating_vio.html
    # https://www.stereolabs.com/docs/ros2/020_zed-node#published-topics
    odom0: zed/zed_node/odom # prefuses IMU data with VIO
    odom0_config: [true,  true,  false,  # X, Y, Z
                  false,  false,  true,  # Roll, Pitch, Yaw
                  false, false, false,   # Vx, Vy, Vz
                  false, false, false,   # Vroll, Vpitch, Vyaw
                  false, false, false]   # Ax, Ay, Az
    odom0_differential: false
    odom0_relative: true
    odom0_queue_size: 2

    imu0: imu/data # from the madgwick filter
    imu0_config: [false, false, false,
                  false,  false,  true,
                  false, false, false,
                  false,  false,  false,
                  false,  false,  false]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false # we could fuse in cmd_vel commands, but they are not very accurate

    # The below is from the GPS demo
    process_noise_covariance: [1e-3, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    1e-3,  0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    1e-3,  0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.3,   0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.3,   0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.01,  0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.5,    0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.5,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.1,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.3,   0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.3,   0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.3,   0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.3,   0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.3,   0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.3]

ekf_filter_node_map:
# This publishes the map->base_link transform
# The position calculated here will probably be discrete, but more accurate
# https://robotics.stackexchange.com/questions/109942/odometry-with-robot-localization-using-gps-and-imu-not-encoders
  ros__parameters:
    frequency: 15.0 # The Jetson struggles to run faster than this
    two_d_mode: true  # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link # base_footprint is used in Gazebo
    world_frame: map

    # https://docs.nav2.org/tutorials/docs/integrating_vio.html
    # https://www.stereolabs.com/docs/ros2/020_zed-node#published-topics
    odom0: zed/zed_node/odom # prefuses IMU data with VIO
    odom0_config: [true,  true,  false,  # X, Y, Z
                  false,  false,  true,  # Roll, Pitch, Yaw
                  false, false, false,   # Vx, Vy, Vz
                  false, false, false,   # Vroll, Vpitch, Vyaw
                  false, false, false]   # Ax, Ay, Az
    odom0_differential: true
    odom0_relative: true
    odom0_queue_size: 2

    odom1: odometry/gps # from the navsat_transform_node
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false # this is the absolute position of the robot

    imu0: imu/data # from the madgwick filter
    imu0_config: [false, false, false,
                  false,  false,  true,
                  false, false, false,
                  false,  false,  false,
                  false,  false,  false]
    imu0_differential: false
    imu0_relative: false # this is the absolute orientation of the robot
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false # we could fuse in cmd_vel commands, but they are not very accurate

    # The below is from the GPS demo
    process_noise_covariance: [1.0,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    1.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    1e-3,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.3,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.3,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.5,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.5,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.1,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.3,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.3,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.3,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.3,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.3,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.3]

navsat_transform:
  ros__parameters:
    frequency: 15.0 # The Jetson struggles to run faster than this
    delay: 3.0
    # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml
    magnetic_declination_radians: 0.18814649 # in Provo
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true # used by the path planners
    use_odometry_yaw: true
    wait_for_datum: false 
