services:
  ros2_ws:
    image: zed_ros2_l4t_36.3.0_sdk_4.2.5 # Replace with your Docker image tag
    container_name: zed-ros2-wrapper
    build: 
      context: .
      dockerfile: Dockerfile.custom-l4t-humble
      args:
        L4T_VERSION: l4t-r36.3.0
        ZED_SDK_MAJOR: 4
        ZED_SDK_MINOR: 2
        ZED_SDK_PATCH: 5
        L4T_MAJOR: 36
        L4T_MINOR: 3
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
      - ../../..:/home/marsrover-zed/zed_ws
    tty: true  # Allows interactive terminal
    entrypoint: ["/bin/bash"]
    restart: always