# Created by Braden Meyers, Mar 2025
services:
  marsrover-zed:
    image: zed_ros2_l4t_36.3.0_sdk_4.2.5
    container_name: marsrover-zed-ct
    build: 
      context: .
      dockerfile: Dockerfile.custom-l4t-humble
      args:
        L4T_VERSION: l4t-r36.3.0
        ZED_SDK_MAJOR: 4
        ZED_SDK_MINOR: 2
        ZED_SDK_PATCH: 5
        L4T_MAJOR: 36
        L4T_MINOR: 3
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: ${DISPLAY}
    volumes:
      - ../../..:/home/marsrover-zed/zed_ws
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
      - /dev:/dev:rw
      - /dev/shm:/dev/shm
      - /etc/udev:/etc/udev:rw
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    estart: always  # Keeps the container running after exit unless you want it to be removed like with --rm
    entrypoint: ["/bin/bash"]