# Created by Nelson Durrant, Nov 2024
# This will build and push a new Docker image to byuawesomerover/marsrover:latest on DockerHub
# whenever a change to docker/Dockerfile is pushed to the main branch.
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - "docker/Dockerfile"

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Quick fix for QEMU error, Feb 2025
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v6
      with:
       context: "{{defaultContext}}:docker"
       platforms: linux/amd64,linux/arm64
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/marsrover:latest
